version: "3.8"

services:
  redis:
    image: redis:7.0.8-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./Local/RedisVolume:/data
      - ./External/Redis/redis.conf:/config/redis.conf:ro
    command: [ "redis-server", "/config/redis.conf" ]

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=z@123456!
    ports:
      - target: 1433
        published: 1434

  kafka:
    image: net-template:kafka-linux-1.0
    build:
      context: .
      dockerfile: External/Kafka/Dockerfile
    environment:
      - KAFKA_OPTS=${KAFKA_OPTS:--Djava.security.auth.login.config=/kafka/custom-config/kafka_server_jaas.conf -Dzookeeper.sasl.client=false -Dzookeeper.ssl.hostnameVerification=false} # Setup SASL using Jaas static file
      - BROKER_ID=1
      - LOCAL_PORT=9092
      - DOCKER_PORT=29092
    volumes:
      - ./External/Kafka/config:/kafka/custom-config:ro
      - ./External/Kafka/scripts:/kafka/scripts:ro
      # - ./Local/KafkaVolume/kafka-data:/kafka-data
      # - ./Local/KafkaVolume/zookeeper-data:/zookeeper-data
      # - ./Local/KafkaVolume/logs:/kafka/logs
    ports:
      - target: 9092
        published: 9092

networks:
  default:
    name: net-template-shared-network
