version: "3.8"

services:
  redis:
    image: redis:7.0.8-alpine
    ports:
      - target: 6379
        published: 6379

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=z@123456!
    ports:
      - target: 1433
        published: 1433

networks:
  default:
    name: net-template-shared-network
